
name: Gradle

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: OS used to run Gradle.
        default: ubuntu-latest

      ref:
        type: string
        description: Branch to check out.
        default: ''

      version:
        type: string
        description: GraalVM version used to run Gradle.
        default: latest

      distribution:
        type: string
        description: GraalVM distribution used to run Gradle.
        default: graalvm-community

      java:
        type: string
        description: Java version used to run Gradle.
        default: 21

      musl:
        type: string
        description: Use MUSL libc.
        default: false

      tasks:
        type: string
        description: Gradle tasks to execute.
        default: ''

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: ''

jobs:
  gradle:
    name: Gradle ${{ inputs.tasks }}
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    defaults:
      run: { shell: bash }
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Up Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ inputs.version }}
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle
          native-image-musl: ${{ inputs.musl }}
      - name: Build Project
        run: ./gradlew --info --stacktrace ${{ inputs.tasks }}
      - name: Check Build
        if: ${{ inputs.check_directory != '' }}
        run: ls -AlF "${{ inputs.check_directory }}"
